[package]
name = "tgit"
version = "0.1.0"
authors = ["tensor-programming <abeltensor@tensor-programming.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
